import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const downloadModernPDF = (result) => {
    if (!result) return;

    const doc = new jsPDF();

    // Header with gradient effect
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PAYSLIP', 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Maharashtra Government Employee', 105, 30, { align: 'center' });

    // Employee Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    let yPos = 50;

    doc.setFont('helvetica', 'bold');
    doc.text('Employee Details:', 20, yPos);
    yPos += 7;

    doc.setFont('helvetica', 'normal');
    doc.text(`Employee Type: ${result.metadata.employeeType}`, 20, yPos);
    doc.text(`City: ${result.metadata.city} (${result.metadata.cityCategory})`, 120, yPos);
    yPos += 7;
    doc.text(`Employee Class: ${result.metadata.employeeClass}`, 20, yPos);
    doc.text(`DA Rate: ${result.metadata.daRate}%`, 120, yPos);
    yPos += 10;

    // Allowances Table
    doc.autoTable({
        startY: yPos,
        head: [['Allowances', 'Amount (₹)']],
        body: [
            ['Basic Salary', result.allowances.basic.toFixed(2)],
            ['Dearness Allowance (DA)', result.allowances.da.toFixed(2)],
            ['House Rent Allowance (HRA)', result.allowances.hra.toFixed(2)],
            ['Transport Allowance (TA)', result.allowances.ta.toFixed(2)],
            ['Per TA', result.allowances.perTA.toFixed(2)],
            ...result.allowances.additionalAllowances.map(a =>
                [a.type, a.calculatedAmount.toFixed(2)]
            ),
            ['TOTAL ALLOWANCES', result.allowances.total.toFixed(2)]
        ],
        headStyles: { fillColor: [59, 130, 246], textColor: 255 },
        footStyles: { fillColor: [229, 231, 235], textColor: 0, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 20, right: 20 }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // Deductions Table
    doc.autoTable({
        startY: yPos,
        head: [['Deductions', 'Amount (₹)']],
        body: [
            ['Professional Tax', result.deductions.professionalTax.toFixed(2)],
            ['GIS', result.deductions.gis.toFixed(2)],
            ...(result.deductions.dcps > 0 ? [['DCPS (NPS)', result.deductions.dcps.toFixed(2)]] : []),
            ...(result.deductions.gpfSubscription > 0 ? [['GPF Subscription', result.deductions.gpfSubscription.toFixed(2)]] : []),
            ...(result.deductions.gpfRecovery > 0 ? [['GPF Recovery', result.deductions.gpfRecovery.toFixed(2)]] : []),
            ...(result.deductions.festivalAdvance > 0 ? [['Festival Advance', result.deductions.festivalAdvance.toFixed(2)]] : []),
            ...(result.deductions.otherAdvances > 0 ? [['Other Advances', result.deductions.otherAdvances.toFixed(2)]] : []),
            ...(result.deductions.otherRecovery > 0 ? [['Other Recovery', result.deductions.otherRecovery.toFixed(2)]] : []),
            ...(result.deductions.incomeTax > 0 ? [['Income Tax', result.deductions.incomeTax.toFixed(2)]] : []),
            ['TOTAL DEDUCTIONS', result.deductions.total.toFixed(2)]
        ],
        headStyles: { fillColor: [239, 68, 68], textColor: 255 },
        footStyles: { fillColor: [229, 231, 235], textColor: 0, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 20, right: 20 }
    });

    yPos = doc.lastAutoTable.finalY + 10;

    // Net Salary
    doc.setFillColor(34, 197, 94);
    doc.rect(20, yPos, 170, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('NET SALARY:', 25, yPos + 10);
    doc.text(`₹ ${result.netSalary.toFixed(2)}`, 185, yPos + 10, { align: 'right' });

    // Footer
    doc.setTextColor(128, 128, 128);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Smart Employee Toolkit', 105, 285, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 290, { align: 'center' });

    doc.save('payslip-modern.pdf');
};

export const downloadTraditionalPDF = (result) => {
    if (!result) return;

    const doc = new jsPDF();

    // Simple header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('PAY SLIP', 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Government of Maharashtra', 105, 30, { align: 'center' });

    doc.line(20, 35, 190, 35);

    let yPos = 45;

    // Employee details in traditional format
    doc.setFontSize(10);
    doc.text(`Employee Type: ${result.metadata.employeeType}`, 20, yPos);
    yPos += 7;
    doc.text(`City: ${result.metadata.city}`, 20, yPos);
    doc.text(`Category: ${result.metadata.cityCategory}`, 120, yPos);
    yPos += 7;
    doc.text(`Class: ${result.metadata.employeeClass}`, 20, yPos);
    doc.text(`DA Rate: ${result.metadata.daRate}%`, 120, yPos);
    yPos += 10;

    doc.line(20, yPos, 190, yPos);
    yPos += 7;

    // Allowances
    doc.setFont('helvetica', 'bold');
    doc.text('ALLOWANCES', 20, yPos);
    doc.text('AMOUNT (₹)', 150, yPos);
    yPos += 7;
    doc.line(20, yPos - 2, 190, yPos - 2);

    doc.setFont('helvetica', 'normal');
    const allowanceItems = [
        ['Basic Salary', result.allowances.basic],
        ['DA', result.allowances.da],
        ['HRA', result.allowances.hra],
        ['TA', result.allowances.ta],
        ['Per TA', result.allowances.perTA],
        ...result.allowances.additionalAllowances.map(a => [a.type, a.calculatedAmount])
    ];

    allowanceItems.forEach(([label, amount]) => {
        doc.text(label, 25, yPos);
        doc.text(amount.toFixed(2), 185, yPos, { align: 'right' });
        yPos += 6;
    });

    doc.line(20, yPos, 190, yPos);
    yPos += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('Total Allowances', 25, yPos);
    doc.text(result.allowances.total.toFixed(2), 185, yPos, { align: 'right' });
    yPos += 10;

    // Deductions
    doc.setFont('helvetica', 'bold');
    doc.text('DEDUCTIONS', 20, yPos);
    doc.text('AMOUNT (₹)', 150, yPos);
    yPos += 7;
    doc.line(20, yPos - 2, 190, yPos - 2);

    doc.setFont('helvetica', 'normal');
    const deductionItems = [
        ['Professional Tax', result.deductions.professionalTax],
        ['GIS', result.deductions.gis],
        ...(result.deductions.dcps > 0 ? [['DCPS', result.deductions.dcps]] : []),
        ...(result.deductions.gpfSubscription > 0 ? [['GPF Subscription', result.deductions.gpfSubscription]] : []),
        ...(result.deductions.gpfRecovery > 0 ? [['GPF Recovery', result.deductions.gpfRecovery]] : []),
        ...(result.deductions.festivalAdvance > 0 ? [['Festival Advance', result.deductions.festivalAdvance]] : []),
        ...(result.deductions.otherAdvances > 0 ? [['Other Advances', result.deductions.otherAdvances]] : []),
        ...(result.deductions.otherRecovery > 0 ? [['Other Recovery', result.deductions.otherRecovery]] : []),
        ...(result.deductions.incomeTax > 0 ? [['Income Tax', result.deductions.incomeTax]] : []),
    ];

    deductionItems.forEach(([label, amount]) => {
        doc.text(label, 25, yPos);
        doc.text(amount.toFixed(2), 185, yPos, { align: 'right' });
        yPos += 6;
    });

    doc.line(20, yPos, 190, yPos);
    yPos += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('Total Deductions', 25, yPos);
    doc.text(result.deductions.total.toFixed(2), 185, yPos, { align: 'right' });
    yPos += 10;

    // Net Salary
    doc.setFontSize(12);
    doc.line(20, yPos, 190, yPos);
    yPos += 8;
    doc.text('NET SALARY', 25, yPos);
    doc.text(`₹ ${result.netSalary.toFixed(2)}`, 185, yPos, { align: 'right' });
    doc.line(20, yPos + 2, 190, yPos + 2);

    // Footer
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, 280, { align: 'center' });

    doc.save('payslip-traditional.pdf');
};
